### ISSUE TITLE
Lock screen & password bug

### ISSUE THREAD

**Issue by gntica** [ingbrzy/MA-XML-8.0-SPANISH#469]
Hello @ingbrzy ,
I have a problem with the spanish language in the last weekly rom. If I try with other language works fine.

In “**Lock screen & password** > **Privacy protection password**” I get this error when I successfully unlock.

![1](https://cloud.githubusercontent.com/assets/23074372/19721353/322da8ca-9b72-11e6-8e6c-4e744cb82009.jpg)

Another possible bug, maybe they are related… because of the "Ñ" letter problematic in code. 
In “**Lock screen & password** > **Screen lock & fingerprint**”.
The “Forgot password” text... see picture.

![2](https://cloud.githubusercontent.com/assets/23074372/19721460/9474c2de-9b72-11e6-96d8-cdad3a0d7859.jpg)

Thank you for your great work ingbrzy!
y gracias a ti también @Infante007 por supuesto :)

**Comment by ingbrzy** [comment]
press "ver resumen" copy it and paste here...

**Comment by gntica** [comment]
I can not do this...
When I press this button, to see the error log, they crash and send me to initial screen “**Lock screen & password**"

In others languages I don´t have this crash, only spanish.
Thank you.

**Comment by ingbrzy** [comment]
what crash? after pressing "Ver resumen" you should see a log...

typo fixed
https://github.com/ingbrzy/MA-XML-8.0-SPANISH/commit/522cecfdce1c0bf1af998b2aff9d3d228a72cf1e

**Comment by gntica** [comment]
Not, goes back in menu options, but dont shows any error log. Sorry.

**Comment by gntica** [comment]
Even if I press "Notificar" I goes back.

**Comment by ingbrzy** [comment]
then use adb and make a log via logcat... I cant help without log...

**Comment by nosijf982** [comment]
10-26 12:52:02.086 25221 25221 E AndroidRuntime: FATAL EXCEPTION: main
10-26 12:52:02.086 25221 25221 E AndroidRuntime: Process: com.android.settings, PID: 25221
10-26 12:52:02.086 25221 25221 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.privacypassword.ModifyAndInstructionPrivacyPassword}: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.ActivityThread.access$900(ActivityThread.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.os.Looper.loop(Looper.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:163)
10-26 12:52:02.086 25221 25221 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=5; index=5
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at com.android.settings.privacypassword.ModifyAndInstructionPrivacyPassword.tq(ModifyAndInstructionPrivacyPassword.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at com.android.settings.privacypassword.ModifyAndInstructionPrivacyPassword.onCreate(ModifyAndInstructionPrivacyPassword.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
10-26 12:52:02.086 25221 25221 E AndroidRuntime:        ... 11 more
10-26 12:52:02.212  1455  3858 E InputDispatcher: channel 'a3eda8 com.android.settings/com.android.settings.SubSettings (server)' ~ Channel is unrecoverably broken and will be disposed!
10-26 12:52:02.212  1455  3858 E InputDispatcher: channel 'b418b12 com.android.settings/com.android.settings.SubSettings (server)' ~ Channel is unrecoverably broken and will be disposed!
10-26 12:52:02.811 25397 25416 E HAL     : hw_get_module_by_class: module name gralloc
10-26 12:52:02.811 25397 25416 E HAL     : hw_get_module_by_class: module name gralloc
10-26 12:52:03.631 25418 25418 E subsystem_ramdump: Unable to open /dev
10-26 12:52:03.631 25418 25418 E subsystem_ramdump: Failed to find pil ramdump

**Comment by gntica** [comment]
Gracias @nosijf982 ahora estoy en la oficina y no puedo ponerme a hacer logcat :)
¿qué movil tienes? el mio es un mi5.

**Comment by nosijf982** [comment]
@gntica Nada 😋, A mi también me ocurre lo mismo vuelve para atrás cuando pongo la contraseña,tengo un Redmi Note 3 Pro

**Comment by Infante007** [comment]
Si es algo general 
Estos días arregle en ajustes muchas líneas que estaban mal .
Puede que arreglase el problema , lo que pasa que saldría en la siguiente rom semanal.
Pero bueno haber que ve @ingbrzy que es  el que sabe.
